Config = {}

Config.ChatReader = false -- for plate scanner via chat
Config.PSDispatch = true -- for plate scanner via dispatch

Config.Cursor = {
    key = {active = true, key1 = 36, key2 = 26}, --Default CTRL+C
}

Config.Keys = {
    Radar = "F6",
    FrontLock = "numpad8",
    RearLock = "numpad5",
    FrontSpeed = "numpad9",
    RearSpeed = "numpad6",
}

Config.PDJobs = {
    ["leo"] = true,
    ["police"] = true,
    ["lspd"] = true,
    ["bcso"] = true,
}

Config.PDCars = {
    [`police`] = true,
    [`police1`] = true,
    [`police2`] = true,
    [`police3`] = true,
    [`police4`] = true,
    [`police5`] = true,
    [`police6`] = true,
    [`police7`] = true,
    [`police8`] = true,
    [`police9`] = true,
    [`policeb`] = true,
    [`polgauntlet`] = true,

    [`rrkurumaxzm`] = true,
    [`rrsultanxzm`] = true,
    [`rrsunriseunmarked`] = true,
    [`rrdominatorunmarked`] = true,
}

Config.FakeNames = {
    first = {
        "Liam",
        "Ben",
        "Robert",
        "Joseph",
        "Charlie",
        "Samuel",
        "Otis",
        "Matt",
        "Russel",
        "Tristan",
        "Bryan",
        "Jeremy",
        "Michael",
        "Owen",
        "Theodore",
        "Leo",
        "Edward",
        "Lewis",
        "Daniel",
        "Garrett",
        "Peter",
        "Stewart",
        "Craig",
        "Ray",
        "Chandler",
        "Jesus",
        "Shawn",
        "Cooper",
        "Arthur",
        "Matthew",
        "Carter",
        "Graham",
        "Oliver",
        "James",
        "Jacob",
        "Ethan",
        "Levi",
        "Sebastian",
        "Jack",
        "Owen",
        "Aiden",
        "Luke",
        "Julian",
        "Isaac",
        "Anthony",
        "Ezra",
        "Charles",
        "Isaiah",
        "Joshua",
        "Nathan",
        "Ryan",
        "Aaron",
        "Ezekiel",
        "Cameron",
        "Colton",
        "Jonathan",
        "Roman",
        "Ian",
        "Dominic",
        "Adam",
        "Wesley",
        "Katrina",
        "Ashley",
        "Maria",
        "Ava",
        "Mollie",
        "Pearl",
        "Scarlet",
        "Mary",
        "Melissa",
        "Vanessa",
        "Rachael",
        "Edith",
        "Mia",
        "Betty",
        "Elizabeth",
        "Gracie",
        "Tabitha",
        "Julie",
        "Susan",
        "Summer",
        "Karen",
        "Alicia",
        "Isabelle",
        "Ellie",
        "Maddie",
        "Sara",
        "Felicia",
        "Darcie",
        "Tanya",
        "Rose",
        "Avery",
        "Sofia",
        "Mila",
        "Layla",
        "Aria",
        "Emily",
        "Madison",
        "Lily",
        "Grace",
        "Violet",
        "Zoey",
        "Chloe",
        "Luna",
        "Abigail",
        "Penelope",
        "Ella",
        "Leah",
        "Victoria",
        "Lucy",
        "Claire",
        "Audrey",
        "Brook",
        "Savannah",
        "Madelyn",
        "Skylar",
        "Allison",
        "Serenity",
        "Anna",
        "Lydia",
        "Clara",
        "Julia",
    },
    last = {
        "Philips",
        "Rogers",
        "Newstead",
        "Jackson",
        "Schmidt",
        "Matthews",
        "Barnett",
        "Ramsey",
        "Turner",
        "Houston",
        "Goodwin",
        "Jennings",
        "Higgins",
        "Kennedy",
        "Walters",
        "Banks",
        "Hopkins",
        "Lawson",
        "Griffith",
        "Newman",
        "Hill",
        "Weber",
        "Welch",
        "Hardwood",
        "Payne",
        "Meyer",
        "Morrison",
        "Lane",
        "Fernandez",
        "Moore",
        "Osborne",
        "Campbell",
        "Chavez",
        "Ortega",
        "Reid",
        "Hudson",
        "Wallace",
        "Davis",
        "Ramirez",
        "Buchanan",
        "Smith",
        "Burns",
        "Peterson",
        "Robinson",
        "Gomez",
        "Harris",
        "Wilson",
        "Brown",
        "Walker",
        "Hall",
        "Reyes",
        "Ortiz",
        "Watson",
        "Ruiz",
        "Perry",
        "Barnes",
        "West",
        "Woods",
        "Freeman",
        "Crawford",
        "Olson",
        "Shaw",
        "Boyd",
        "Weaver",
        "Pierce",
        "Peters",
        "Hoffman",
        "Watkins",
        "Burke",
        "Walsh",
        "Schultz",
        "Wade",
        "Powers",
        "Watts",
        "Benson",
        "Reeves",
        "Love",
        "Robbins",
        "Cross",
        "McGee",
        "Goodman",
        "Fischer",
        "Mullins",
        "Tate",
        "Schroeder",
        "Floyd",
        "Hartman",
        "Sparks",
        "Stokes",
        "Weiss",
        "Poole",
        "Bradford",
        "Atkins",
        "Hensley",
        "Winters",
        "Crosby",
        "Peck",
        "Boyle",
        "Sampson",
    },
}
